export const UPDATE_PUBLIC_PRICE = 'UPDATE_PUBLIC_PRICE';
export const UPDATE_GROUP_PRICE = 'UPDATE_GROUP_PRICE';
export const UPDATE_BONUS = 'UPDATE_BONUS';
export const UPDATE_DISCOUNT = 'UPDATE_DISCOUNT';
export const COMPUTE_FIELD = 'COMPUTE_FIELD';
export const RECEIVE_FIELD_VALUE = 'RECEIVE_FIELD_VALUE';
